import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const required = [
  "server.mjs",
  "public/index.html",
  "public/app.js",
  "public/styles.css",
  "public/icons/open-book.svg",
  "public/icons/app-icon.ico",
  "server/modules/project.mjs",
  "server/modules/memory.mjs",
  "server/modules/pipeline.mjs",
  "server/modules/quality.mjs",
  "server/modules/export.mjs",
  "server/modules/codex-runner.mjs",
  "public/modules/state.js",
  "public/modules/api.js",
  "public/modules/render.js",
  "public/modules/actions.js",
  "public/modules/panels.js",
  "scripts/e2e.mjs",
  "RELEASE_NOTES.md",
  "GITHUB_RELEASE_TEMPLATE.md",
  "V1_RELEASE_CHECKLIST.md",
  "electron/main.mjs",
  "README.md",
  "使用教程.md",
  "ROADMAP.md",
  "CURRENT_ITERATION.md",
  ".gitignore"
];

const missing = [];
for (const file of required) {
  try {
    await fs.access(path.join(root, file));
  } catch {
    missing.push(file);
  }
}

const pkg = JSON.parse(await fs.readFile(path.join(root, "package.json"), "utf8"));
const scripts = ["start", "desktop", "pack:win", "check", "smoke", "regression", "e2e", "acceptance", "prepare:github"];
const missingScripts = scripts.filter((name) => !pkg.scripts?.[name]);

const indexHtml = await fs.readFile(path.join(root, "public/index.html"), "utf8");
const appJs = await fs.readFile(path.join(root, "public/app.js"), "utf8");
const stylesCss = await fs.readFile(path.join(root, "public/styles.css"), "utf8");
const serverMjs = await fs.readFile(path.join(root, "server.mjs"), "utf8");
const electronMainMjs = await fs.readFile(path.join(root, "electron/main.mjs"), "utf8");
const readmeMd = await fs.readFile(path.join(root, "README.md"), "utf8");
const tutorialMd = await fs.readFile(path.join(root, "使用教程.md"), "utf8");
const roadmapMd = await fs.readFile(path.join(root, "ROADMAP.md"), "utf8");
const currentIterationMd = await fs.readFile(path.join(root, "CURRENT_ITERATION.md"), "utf8");
const releaseNotesMd = await fs.readFile(path.join(root, "RELEASE_NOTES.md"), "utf8");
const releaseTemplateMd = await fs.readFile(path.join(root, "GITHUB_RELEASE_TEMPLATE.md"), "utf8");
const v1ChecklistMd = await fs.readFile(path.join(root, "V1_RELEASE_CHECKLIST.md"), "utf8");

const requiredUiMarkers = [
  ["index.html", "id=\"toggleAiConfig\""],
  ["index.html", "id=\"experienceMode\""],
  ["index.html", "data-experience-mode=\"beginner\""],
  ["index.html", "data-experience-mode=\"expert\""],
  ["index.html", "id=\"onboardingOverlay\""],
  ["index.html", "id=\"openOnboarding\""],
  ["index.html", "data-onboarding-action=\"idea\""],
  ["index.html", "data-onboarding-action=\"manual\""],
  ["index.html", "data-onboarding-action=\"existing\""],
  ["index.html", "data-onboarding-action=\"demo\""],
  ["index.html", "one-stop-guide"],
  ["index.html", "id=\"nextStepBanner\""],
  ["index.html", "beginner-step-card"],
  ["index.html", "id=\"nextStepAction\""],
  ["index.html", "id=\"pathReadinessPanel\""],
  ["index.html", "id=\"runPathReadiness\""],
  ["index.html", "id=\"projectDashboard\""],
  ["index.html", "id=\"firstChapterStarter\""],
  ["index.html", "id=\"writingQualityLoop\""],
  ["index.html", "id=\"runWritingQualityLoop\""],
  ["index.html", "id=\"publishCenter\""],
  ["index.html", "id=\"runPublishCenter\""],
  ["index.html", "id=\"pipelineProgress\""],
  ["index.html", "id=\"incubationResultPanel\""],
  ["index.html", "id=\"incubationOpenFile\""],
  ["index.html", "id=\"pipelinePreflightPanel\""],
  ["index.html", "data-flow-step=\"prepare\""],
  ["index.html", "data-flow-step=\"memory\""],
  ["index.html", "id=\"smartPrimaryAction\""],
  ["index.html", "id=\"smartPublishAction\""],
  ["index.html", "id=\"toggleQuickOpen\""],
  ["index.html", "id=\"toggleAdvancedTools\""],
  ["index.html", "creation-mode-tabs"],
  ["index.html", "灵感孵化"],
  ["index.html", "精准创建"],
  ["index.html", "data-creation-mode=\"idea\""],
  ["index.html", "data-creation-mode=\"manual\""],
  ["app.js", "function renderSmartGuide"],
  ["app.js", "function setExperienceMode"],
  ["app.js", "function renderExperienceMode"],
  ["app.js", "function nextStepState"],
  ["app.js", "function renderNextStep"],
  ["app.js", "function runNextStepAction"],
  ["app.js", "function actionableErrorMessage"],
  ["app.js", "function refreshPathReadiness"],
  ["app.js", "function renderPathReadiness"],
  ["app.js", "function refreshProjectDashboard"],
  ["app.js", "function renderProjectDashboard"],
  ["app.js", "function renderFirstChapterStarter"],
  ["app.js", "function runWritingQualityLoop"],
  ["app.js", "function renderWritingQualityLoop"],
  ["app.js", "function runPublishCenter"],
  ["app.js", "function renderPublishCenter"],
  ["app.js", "function setPipelineProgress"],
  ["app.js", "function renderPipelineProgress"],
  ["app.js", "function extractIncubationSummary"],
  ["app.js", "function renderIncubationResult"],
  ["app.js", "function pipelinePreflightState"],
  ["app.js", "function renderPipelinePreflight"],
  ["app.js", "function runSmartPrimaryAction"],
  ["app.js", "function openOnboarding"],
  ["app.js", "function closeOnboarding"],
  ["app.js", "function handleOnboardingAction"],
  ["app.js", "function maybeShowOnboarding"],
  ["app.js", "function toggleAdvancedTools"],
  ["app.js", "function setCreationMode"],
  ["app.js", "function guideToIdeaInput"],
  ["app.js", "function guideToProjectStart"],
  ["app.js", "function guideToChapterBrief"],
  ["app.js", "function openGuidedToolPanel"],
  ["app.js", "function guideToStyleInput"],
  ["app.js", "function guideToKnowledgeInput"],
  ["app.js", "function guideToSyncReviewItems"],
  ["app.js", "function guideToLatestResult"],
  ["app.js", "function guideToVersionHistory"],
  ["app.js", "function renderMarkdownPreview"],
  ["app.js", "function setEditorMode"],
  ["app.js", "function selectedChapter"],
  ["app.js", "function renderChapterFlow"],
  ["app.js", "function chapterFlowResultState"],
  ["app.js", "function openChapterFlowResult"],
  ["app.js", "function updateActiveChapterStatus"],
  ["app.js", "function runChapterFlowAction"],
  ["app.js", "function confirmDraftOverwrite"],
  ["app.js", "function isDraftDirty"],
  ["app.js", "function beginOperationFeedback"],
  ["app.js", "function finishOperationFeedback"],
  ["app.js", "function operationResultLocation"],
  ["app.js", "function operationContinuityState"],
  ["app.js", "function openOperationResult"],
  ["app.js", "function runOperationNext"],
  ["app.js", "如果刚更新过项目，请刷新页面后再试"],
  ["index.html", "id=\"draftPreview\""],
  ["index.html", "id=\"chapterFlowPanel\""],
  ["index.html", "id=\"chapterFlowPrimary\""],
  ["index.html", "id=\"chapterFlowBack\""],
  ["index.html", "id=\"chapterFlowResult\""],
  ["index.html", "id=\"chapterFlowResultAction\""],
  ["index.html", "id=\"operationFeedback\""],
  ["index.html", "id=\"operationResultAction\""],
  ["index.html", "id=\"operationNextAction\""],
  ["index.html", "data-tool-panel=\"text-actions\""],
  ["index.html", "data-editor-mode=\"preview\""],
  ["styles.css", ".text-actions-panel"],
  ["styles.css", ".chapter-flow-panel"],
  ["styles.css", ".chapter-flow-result"],
  ["styles.css", ".chapter-flow-actions"],
  ["styles.css", ".beginner-mode .toolbox {"],
  ["styles.css", ".beginner-mode .next-step-banner"],
  ["styles.css", ".editor-section > .one-stop-guide"],
  ["styles.css", ".operation-feedback"],
  ["styles.css", ".operation-feedback-actions"],
  ["styles.css", ".is-loading"],
  ["server.mjs", "cache-control"],
  ["server.mjs", "接口不存在：${req.method} ${url.pathname}"],
  ["styles.css", ".markdown-editor"],
  ["styles.css", ".markdown-preview"],
  ["styles.css", ".one-stop-guide"],
  ["styles.css", ".experience-mode-toggle"],
  ["styles.css", ".top-actions > button,"],
  ["styles.css", "height: var(--top-action-height)"],
  ["styles.css", "align-self: stretch"],
  ["styles.css", "place-items: center"],
  ["styles.css", ".top-actions .experience-mode-toggle button"],
  ["styles.css", ".beginner-mode"],
  ["styles.css", ".expert-mode"],
  ["styles.css", "grid-template-columns: minmax(132px, 0.75fr) repeat(5, minmax(92px, 1fr))"],
  ["styles.css", ".path-readiness-panel"],
  ["styles.css", ".project-dashboard"],
  ["styles.css", ".first-chapter-starter"],
  ["styles.css", ".writing-quality-loop"],
  ["styles.css", ".publish-center"],
  ["styles.css", ".next-step-banner"],
  ["styles.css", ".incubation-result-panel"],
  ["styles.css", ".preflight-panel"],
  ["styles.css", ".pipeline-progress"],
  ["styles.css", ".flow-step.active"],
  ["styles.css", ".flow-step.done"],
  ["styles.css", ".onboarding-overlay"],
  ["styles.css", ".onboarding-card"],
  ["styles.css", ".onboarding-choice"],
  ["styles.css", ".advanced-tools-collapsed"],
  ["styles.css", ".creation-mode-tabs"],
  ["styles.css", ".needs-attention"],
  ["styles.css", ".guide-steps span.active"],
  ["styles.css", ".beginner-mode #smartAdvancedAction"],
  ["styles.css", ".beginner-mode.has-project .creation-start-panel"],
  ["styles.css", "@media (max-width: 420px)"],
  ["app.js", "function renderGuideSteps"],
  ["app.js", "dataset.smartPrimaryAction"],
  ["app.js", "classList.toggle(\"has-project\""],
  ["styles.css", "z-index: 50"],
  ["styles.css", "z-index: 60"],
  ["index.html", "rel=\"icon\""],
  ["index.html", "/icons/open-book.svg"],
  ["index.html", "brand-icon"],
  ["index.html", "id=\"topAiConfig\""],
  ["index.html", "id=\"toggleNewProject\""],
  ["index.html", "id=\"newProjectBody\""],
  ["index.html", "id=\"createDemoProject\""],
  ["index.html", "sidebar-idea-panel"],
  ["index.html", "id=\"toggleLeftPane\""],
  ["index.html", "id=\"toggleRightPane\""],
  ["index.html", "top-pane-toggle"],
  ["index.html", "id=\"autosaveStatus\""],
  ["index.html", "id=\"compareLatestVersion\""],
  ["index.html", "id=\"globalSearchInput\""],
  ["index.html", "id=\"taskCenterPanel\""],
  ["index.html", "id=\"taskKindFilter\""],
  ["index.html", "id=\"taskStatusFilter\""],
  ["index.html", "id=\"taskAutoRefresh\""],
  ["index.html", "id=\"taskDetailPanel\""],
  ["index.html", "Codex 运行历史"],
  ["index.html", "id=\"narrativeRadarPanel\""],
  ["index.html", "id=\"toggleMoreTools\""],
  ["index.html", "id=\"moreToolMenu\""],
  ["index.html", "data-toolbox-group=\"write\""],
  ["index.html", "data-tool-panel"],
  ["index.html", "data-tool-panel=\"global-search\""],
  ["index.html", "data-tool-panel=\"task-center\""],
  ["index.html", "data-tool-panel=\"narrative-radar\""],
  ["index.html", "data-tool-panel=\"revision-publish\""],
  ["index.html", "data-tool-panel=\"project-maintenance\""],
  ["index.html", "data-tool-panel=\"style-lab\""],
  ["index.html", "data-tool-panel=\"memory-recall\""],
  ["index.html", "data-tool-panel=\"story-bible\""],
  ["index.html", "id=\"storyBiblePanel\""],
  ["index.html", "data-tool-group=\"project quality\" data-tool-panel=\"style-lab\""],
  ["index.html", "data-tool-group=\"project quality\" data-tool-panel=\"memory-recall\""],
  ["index.html", "data-tool-group=\"write revision quality\" data-tool-panel=\"sync-review\""],
  ["index.html", "本章必读"],
  ["index.html", "id=\"previewMemoryRecall\""],
  ["index.html", "id=\"analyzeStyleProfile\""],
  ["index.html", "id=\"runFinalPublishCheck\""],
  ["index.html", "id=\"createReleaseBackup\""],
  ["index.html", "id=\"generateReleasePackage\""],
  ["index.html", "id=\"generateReleaseNotes\""],
  ["index.html", "id=\"runMemorySchemaCheck\""],
  ["index.html", "id=\"generateDiagnosticsReport\""],
  ["index.html", "id=\"runProseQualityReview\""],
  ["index.html", "id=\"exportPortableProject\""],
  ["index.html", "id=\"repairMemoryJson\""],
  ["index.html", "id=\"runProjectIntegrityCheck\""],
  ["index.html", "id=\"diagnosticsPanel\""],
  ["app.js", "function previewSelectedSyncReview"],
  ["app.js", "data-sync-preview"],
  ["app.js", "sync-diff-preview"],
  ["server.mjs", "buildStateSyncDiffPreview"],
  ["server.mjs", "parts[4] === \"preview\""],
  ["index.html", "项目维护"],
  ["app.js", "function toggleNewProjectPanel"],
  ["app.js", "function togglePane"],
  ["app.js", "function setActiveToolPanel"],
  ["app.js", "function scheduleAutosave"],
  ["app.js", "function createDemoProject"],
  ["app.js", "function runGlobalSearch"],
  ["app.js", "function renderTaskCenter"],
  ["app.js", "function filteredTasks"],
  ["app.js", "function renderTaskDetail"],
  ["app.js", "function loadTaskDetail"],
  ["app.js", "function retryTask"],
  ["app.js", "function cancelTask"],
  ["app.js", "function setTaskAutoRefresh"],
  ["app.js", "function renderNarrativeRadar"],
  ["app.js", "function runNarrativeRadar"],
  ["app.js", "function pinMemoryRecallItem"],
  ["app.js", "function excludeMemoryRecallItem"],
  ["app.js", "function loadStoryBible"],
  ["app.js", "function saveStoryBibleEntry"],
  ["app.js", "function firstRepairableConflict"],
  ["app.js", "function createConflictRepairPlan"],
  ["app.js", "function applyConflictRepair"],
  ["app.js", "function runFinalPublishCheck"],
  ["app.js", "function createReleaseBackup"],
  ["app.js", "function generateReleasePackage"],
  ["app.js", "function generateReleaseNotes"],
  ["app.js", "function runMemorySchemaCheck"],
  ["app.js", "function generateDiagnosticsReport"],
  ["app.js", "function runProseQualityReview"],
  ["app.js", "function exportPortableProject"],
  ["app.js", "function repairMemoryJson"],
  ["app.js", "function runProjectIntegrityCheck"],
  ["app.js", "data-memory-pin"],
  ["app.js", "data-memory-exclude"],
  ["app.js", "data-conflict-repair-plan"],
  ["app.js", "data-conflict-repair-apply"],
  ["server.mjs", "memory-pins"],
  ["server.mjs", "memory-exclusions"],
  ["server.mjs", "story-bible"],
  ["server.mjs", "parts[4] === \"repair-plan\""],
  ["server.mjs", "parts[4] === \"apply\""],
  ["server.mjs", "image/svg+xml"],
  ["server.mjs", "image/x-icon"],
  ["server.mjs", "function readStoryBible"],
  ["server.mjs", "MEMORY_PINS_FILE"],
  ["server.mjs", "MEMORY_EXCLUSIONS_FILE"],
  ["server.mjs", "parts[3] === \"search\""],
  ["server.mjs", "parts[3] === \"tasks\""],
  ["server.mjs", "parts[3] === \"readiness\""],
  ["server.mjs", "parts[3] === \"dashboard\""],
  ["server.mjs", "parts[3] === \"writing-quality-loop\""],
  ["server.mjs", "parts[3] === \"publish-center\""],
  ["server.mjs", "function buildPathReadinessReport"],
  ["server.mjs", "function buildProjectDashboard"],
  ["server.mjs", "function runWritingQualityLoop"],
  ["server.mjs", "function runPublishCenter"],
  ["server.mjs", "platformPublishTemplate"],
  ["server.mjs", "styleAlignment"],
  ["server.mjs", "reason: \"before_chapter_write\""],
  ["server.mjs", "function filterProjectTasks"],
  ["server.mjs", "function readProjectTaskDetail"],
  ["server.mjs", "function retryProjectTask"],
  ["server.mjs", "function cancelProjectTask"],
  ["server.mjs", "function runFinalPublishCheck"],
  ["server.mjs", "function createReleaseBackup"],
  ["server.mjs", "function generateReleasePackage"],
  ["server.mjs", "function generateReleaseNotes"],
  ["server.mjs", "function validateProjectMemorySchemas"],
  ["server.mjs", "function generateDiagnosticsReport"],
  ["server.mjs", "function createDemoProject"],
  ["server.mjs", "function writeDemoAcceptanceReport"],
  ["server.mjs", "function analyzeProseQuality"],
  ["server.mjs", "function generateProseQualityReport"],
  ["server.mjs", "function exportPortableProject"],
  ["server.mjs", "function repairProjectMemoryJson"],
  ["server.mjs", "function runProjectIntegrityCheck"],
  ["server.mjs", "url.pathname === \"/api/demo-project\""],
  ["server.mjs", "parts[3] === \"prose-quality\""],
  ["server.mjs", "parts[3] === \"portable-export\""],
  ["server.mjs", "parts[3] === \"memory-repair\""],
  ["server.mjs", "parts[3] === \"integrity-check\""],
  ["server.mjs", "parts[3] === \"memory-schema-check\""],
  ["server.mjs", "parts[3] === \"diagnostics-report\""],
  ["server.mjs", "parts[3] === \"publish-final-check\""],
  ["server.mjs", "parts[3] === \"release-backup\""],
  ["server.mjs", "parts[3] === \"release-package\""],
  ["server.mjs", "parts[3] === \"release-notes\""],
  ["server.mjs", "parts[5] === \"retry\""],
  ["server.mjs", "parts[5] === \"cancel\""],
  ["server.mjs", "TASK_INDEX_FILE"],
  ["server.mjs", "function recordProjectTask"],
  ["server.mjs", "function analyzeStyleProfile"],
  ["server.mjs", "function recallStructuredMemory"],
  ["server.mjs", "recalledMemory.ranked"],
  ["server.mjs", "memory-recall"],
  ["server.mjs", "style-profile"],
  ["README.md", "09_运行时/tasks.json"],
  ["README.md", "任务取消"],
  ["README.md", "失败任务一键重试"],
  ["README.md", "发布前总检查"],
  ["README.md", "完整备份包"],
  ["README.md", "JSON schema 校验"],
  ["README.md", "故障诊断报告"],
  ["README.md", "演示小说项目"],
  ["README.md", "降 AI 感专项修订"],
  ["README.md", "项目导入/导出"],
  ["README.md", "记忆 JSON 自动修复"],
  ["README.md", "v1.0.0"],
  ["README.md", "v0.3.0"],
  ["README.md", "memory_pins.json"],
  ["README.md", "memory_exclusions.json"],
  ["README.md", "故事圣经"],
  ["README.md", "记忆冲突修复"],
  ["README.md", "ROADMAP.md"],
  ["ROADMAP.md", "v0.2.0"],
  ["ROADMAP.md", "v0.4.0"],
  ["ROADMAP.md", "失败任务一键重试。已完成。"],
  ["ROADMAP.md", "发布前总检查：章节连续、标题、字数、简介、标签、封面描述。已完成。"],
  ["ROADMAP.md", "JSON schema 校验长期记忆文件。已完成。"],
  ["ROADMAP.md", "v0.7.0"],
  ["ROADMAP.md", "一键体验/演示项目。已完成。"],
  ["ROADMAP.md", "v0.8.0"],
  ["ROADMAP.md", "降 AI 感专项修订。已完成。"],
  ["ROADMAP.md", "v0.9.0"],
  ["ROADMAP.md", "项目导入/导出。已完成。"],
  ["ROADMAP.md", "v1.0.0"],
  ["ROADMAP.md", "正式发布版。已完成。"],
  ["ROADMAP.md", "召回结果手动钉选：把人物、伏笔、承诺固定为本章必读。已完成。"],
  ["CURRENT_ITERATION.md", "当前迭代：v1.0.0"],
  ["CURRENT_ITERATION.md", "正式发布版"],
  ["CURRENT_ITERATION.md", "GitHub Release"],
  ["CURRENT_ITERATION.md", "Windows x64"],
  ["RELEASE_NOTES.md", "v1.0.0"],
  ["GITHUB_RELEASE_TEMPLATE.md", "本地小说工坊 v1.0.0"],
  ["V1_RELEASE_CHECKLIST.md", "正式发布检查清单"],
  ["server.mjs", "parts[3] === \"narrative-radar\""],
  ["server.mjs", "function analyzeNarrativeRadar"],
  ["electron/main.mjs", "app-icon.ico"],
  ["styles.css", ".app-shell.left-collapsed"],
  ["styles.css", ".brand-icon"],
  ["styles.css", ".app-shell.left-collapsed .workspace"],
  ["styles.css", ".app-shell.right-collapsed"],
  ["styles.css", ".top-pane-toggle"],
  ["styles.css", ".top-ai-config"],
  ["styles.css", ".more-tool-menu"],
  ["styles.css", ".tool-panel-toggle"]
];

const forbiddenUnguidedGuards = [
  "return setStatus(\"请先选择项目。\", \"error\")",
  "return setStatus(\"请先打开一个正文文件。\", \"error\")",
  "return setStatus(\"请至少勾选一项同步内容。\", \"error\")",
  "return setStatus(\"还没有可对照的历史版本。\", \"error\")",
  "return setStatus(\"还没有可打开的结果文件。\", \"error\")"
];

const forbiddenLayoutMarkers = [
  ".advanced-tools-collapsed [data-tool-panel=\"chapter-board\"].tool-panel-collapsed",
  ".advanced-tools-collapsed [data-tool-panel=\"sync-review\"].tool-panel-collapsed"
];

const forbiddenUiMarkers = [
  ["index.html", "data-tool-panel=\"ai-settings\""],
  ["index.html", "data-tool-panel=\"idea\""],
  ["index.html", "data-toolbox-group=\"all\""],
  ["index.html", "pane-edge-toggle"],
  ["styles.css", ".pane-edge-toggle"],
  ["index.html", ["造", "梦", "工", "坊"].join("")],
  ["app.js", ["造", "梦", "工", "坊"].join("")],
  ["server.mjs", ["造", "梦", "工", "坊"].join("")],
  ["README.md", ["造", "梦", "工", "坊"].join("")],
  ["使用教程.md", ["造", "梦", "工", "坊"].join("")],
  ["server.mjs", ["I", "n", "k", "O", "S"].join("")],
  ["README.md", ["I", "n", "k", "O", "S"].join("")],
  ["使用教程.md", ["I", "n", "k", "O", "S"].join("")]
];

function sourceFor(file) {
  if (file === "index.html") return indexHtml;
  if (file === "app.js") return appJs;
  if (file === "server.mjs") return serverMjs;
  if (file === "electron/main.mjs") return electronMainMjs;
  if (file === "README.md") return readmeMd;
  if (file === "使用教程.md") return tutorialMd;
  if (file === "ROADMAP.md") return roadmapMd;
  if (file === "CURRENT_ITERATION.md") return currentIterationMd;
  if (file === "RELEASE_NOTES.md") return releaseNotesMd;
  if (file === "GITHUB_RELEASE_TEMPLATE.md") return releaseTemplateMd;
  if (file === "V1_RELEASE_CHECKLIST.md") return v1ChecklistMd;
  return stylesCss;
}

const missingUiMarkers = requiredUiMarkers
  .filter(([file, marker]) => {
    return !sourceFor(file).includes(marker);
  })
  .map(([file, marker]) => `${file}:${marker}`);

const presentForbiddenUiMarkers = forbiddenUiMarkers
  .filter(([file, marker]) => {
    return sourceFor(file).includes(marker);
  })
  .map(([file, marker]) => `${file}:${marker}`);

const presentUnguidedGuards = forbiddenUnguidedGuards.filter((marker) => appJs.includes(marker));
const presentForbiddenLayoutMarkers = forbiddenLayoutMarkers.filter((marker) => stylesCss.includes(marker));
const toolboxTabsIndex = indexHtml.indexOf("id=\"toolboxTabs\"");
const operationFeedbackIndex = indexHtml.indexOf("id=\"operationFeedback\"");
const firstToolPanelIndex = indexHtml.indexOf("data-tool-panel=\"project-status\"");
const operationFeedbackPlacementOk = toolboxTabsIndex >= 0
  && operationFeedbackIndex > toolboxTabsIndex
  && operationFeedbackIndex < firstToolPanelIndex;

if (missing.length || missingScripts.length || missingUiMarkers.length || presentForbiddenUiMarkers.length || presentUnguidedGuards.length || presentForbiddenLayoutMarkers.length || !operationFeedbackPlacementOk) {
  console.error(JSON.stringify({ ok: false, missing, missingScripts, missingUiMarkers, presentForbiddenUiMarkers, presentUnguidedGuards, presentForbiddenLayoutMarkers, operationFeedbackPlacementOk }, null, 2));
  process.exit(1);
}

console.log(JSON.stringify({ ok: true, checkedFiles: required.length, checkedScripts: scripts.length, checkedUiMarkers: requiredUiMarkers.length, checkedForbiddenUiMarkers: forbiddenUiMarkers.length, checkedUnguidedGuards: forbiddenUnguidedGuards.length, checkedLayoutGuards: forbiddenLayoutMarkers.length, operationFeedbackPlacementOk }, null, 2));
